### ISSUE TITLE
Empty symbol table in listing

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep10suite#2]
If a source program does not use symbols then the .pepl listing file should not include an empty symbol table.

**Comment by Matthew-McRaven** [comment]
Works correctly in Pep9, does not work in Pep10.

**Comment by Matthew-McRaven** [comment]
Fixed in 75719bb882e1f9bad8a15773c6ae31e2f45ab449. When we eventually merge MacroAsm into master, this bug will disappear entirely.
